FROM node:18 as git_stage

WORKDIR /app
RUN apt-get update && apt-get install -y git && apt-get purge -y --auto-remove  && rm -rf /var/lib/apt/lists/*
ARG GIT_TAG="v1.0.1"
RUN git clone --branch v1.0.1 --single-branch https://github.com/DCGM/mapstitcher.git
RUN wget https://github.com/DCGM/mapstitcher/releases/download/v1.0.0/outdoor_ds.ckpt && mkdir -p weights && mv outdoor_ds.ckpt weights/
RUN wget https://download.pytorch.org/models/raft_large_C_T_SKHT_V2-ff5fadd5.pth && mkdir -p weights && mv raft_large_C_T_SKHT_V2-ff5fadd5.pth weights/

########################################################################################

FROM python:3.10-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV DEBIAN_FRONTEND=noninteractive

# dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    libopenjp2-tools \
    git \
    libgl1 \
    libglib2.0-0 \
    && rm -rf /var/lib/apt/lists/*

# mapstitcher
WORKDIR /app/mapstitcher

COPY --from=git_stage app/mapstitcher/requirements.txt ./requirements.txt
RUN pip install -r requirements.txt

COPY --from=git_stage app/mapstitcher ./
COPY entrypoint_oneshot.sh /app/entrypoint_oneshot.sh
COPY entrypoint_service.sh /app/entrypoint_service.sh
RUN chmod +x /app/entrypoint_oneshot.sh /app/entrypoint_service.sh

# run
CMD ["python3", "image_stitch_batch.py", "--path", "/test_data/", "--output", "/data/stitched.jp2"]
